global:
  scrape_interval: 5s

scrape_configs:
#  - job_name: 'fastapi-app'
#    metrics_path: /metrics
#    static_configs:
#      - targets: ['fastapi-app:8000']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8888']
  - job_name: 'tempo-metrics'
    static_configs:
      - targets: ['tempo:3200']